### ISSUE TITLE
LineGraph display 'No Data Available' message instead of blank graph

### ISSUE THREAD

**Issue by MichaelRowden** [carbon-design-system/carbon-addons-data-viz-react#19]
When the LineGraph is supplied empty/no data, instead of showing a blank graph could we have it display a message such as 'No Data Available'?

**Comment by tay-aitken** [comment]
Hi @MichaelRowden 👋 I am suggesting the following below. I believe @tw15egan will be making a version of this that can be implemented—TJ correct me if I that's wrong.

Graph will take on a disabled look (@ 30% opacity) and text will be displayed instead of data.
![style-base-graph-1](https://user-images.githubusercontent.com/29312997/30926173-ec4e5870-a379-11e7-9d01-bc95a127b063.png)

**Comment by tw15egan** [comment]
Will make these changes this sprint

**Comment by MichaelRowden** [comment]
@tay-aitken Looks good, really like the disabled look 👍

**Comment by tw15egan** [comment]
Closed via https://github.com/carbon-design-system/carbon-addons-data-viz-react/pull/22
